# -*- coding: utf-8 -*-
"""ChurnAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dp7NARiQ-gEHb3oyqKhGb0ETdsIjAGoz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/telecom_customer - Sheet1.csv')

df.head()

df.isnull().sum()

df.describe()

df['TotalCharges'] = df['TotalCharges'].replace(' ', '0')
df['TotalCharges'] = df['TotalCharges'].astype(float)

df.info()

df.describe() #only for int

df.describe(include=object)

def convert(value):
  if value == 1:
    return "Yes"
  else:
    return "No"
df['SeniorCitizen'] = df['SeniorCitizen'].apply(convert)

df.head()

ax=sns.countplot(data=df,x='Churn')
ax.set_title('Churn Count')
ax.bar_label(ax.containers[0])
ax.set_xlabel('Churn')
ax.set_ylabel('Count')

gb = df.groupby('Churn').agg({'Churn':'count'})
gb

gb = df.groupby('Churn').agg({'Churn':'count'})
plt.pie(gb['Churn'],labels = gb.index,autopct="%1.2f%%")
plt.title('Churn Count')
plt.show()

"""**26.5 Percent Customer Churn Out**"""

df.head()

"""**Customer Churn By Gender**"""

ax = sns.countplot(x="gender",data=df , hue='Churn')
for bars in ax.containers :
  ax.bar_label(bars)

plt.title("Customer Churn Count By Gender")
plt.show()

"""**Female Customer is More Churn Out Then Male Customer **"""

ax = sns.countplot(x="SeniorCitizen",data=df , hue='Churn')
for bars in ax.containers :
  ax.bar_label(bars)

plt.title("Customer Churn Count By SeniorCitizen")
plt.show()

plt.figure(figsize=(10,8))
sns.histplot(data=df,x='tenure',hue='Churn')
plt.show()

ax = sns.countplot(x="Contract",data=df , hue='Churn')
for bars in ax.containers :
  ax.bar_label(bars)

plt.title("Customer Churn Count By Contract")
plt.show()

df.columns

# List of categorical service-related columns to visualize
cols = ['PhoneService', 'MultipleLines', 'InternetService',
        'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
        'TechSupport', 'StreamingTV', 'StreamingMovies']

# Create a 3x3 grid of subplots (one plot per column)
fig, axes = plt.subplots(3, 3, figsize=(18, 14))

# Flatten 2D axes array into 1D for easy iteration
axes = axes.flatten()

# Loop over each column and its corresponding subplot
for i, col in enumerate(cols):

    # sns.countplot automatically counts categories
    # hue='Churn' splits each bar into Churn=Yes / Churn=No
    sns.countplot(
        data=df,
        x=col,
        hue='Churn',                          # Split bars by Churn status
        palette={'No': 'steelblue',           # Non-churned customers → blue
                 'Yes': 'tomato'},            # Churned customers → red
        ax=axes[i],                           # Draw on the i-th subplot
        edgecolor='white'                     # White edge between bars for clarity
    )

    # Set subplot title to the column name
    axes[i].set_title(col, fontsize=13, fontweight='bold', pad=10)

    axes[i].set_xlabel('')                      # Category names are self-explanatory
    axes[i].set_ylabel('Count', fontsize=10)    # Y-axis = frequency count

    # Keep x-axis labels horizontal (no tilt)
    for label in axes[i].get_xticklabels():
        label.set_rotation(0)                   # No rotation — labels stay flat
        label.set_ha('center')                  # Center-align each label under its bar

    # Wrap long label text with line break to prevent overlap
    # e.g. "No internet service" → "No internet\nservice"
    axes[i].set_xticklabels([label.get_text().replace(' ', '\n')
                              for label in axes[i].get_xticklabels()])

    # Annotate each bar with its count value on top
    for bar in axes[i].patches:
        height = bar.get_height()

        # Only label bars that have a visible height (skip empty bars)
        if height > 0:
            axes[i].annotate(
                f'{int(height)}',                                    # Display the count
                xy=(bar.get_x() + bar.get_width() / 2, height),     # Center-top of bar
                xytext=(0, 4),                                       # Nudge text 4pts above bar
                textcoords='offset points',
                ha='center', va='bottom', fontsize=8
            )

    # Show legend only on the first subplot to avoid repetition
    if i == 0:
        axes[i].legend(title='Churn', fontsize=9, title_fontsize=10)
    else:
        axes[i].get_legend().remove()           # Remove legend from all other subplots

# Master title for the entire figure
fig.suptitle('Service Features Distribution by Churn', fontsize=16, fontweight='bold', y=1.01)

# Add a single shared legend outside the plot area (bottom center)
handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, title='Churn', loc='lower center',
           ncol=2, fontsize=11, title_fontsize=12, bbox_to_anchor=(0.5, -0.02))

# Auto-adjust spacing between subplots
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,8))
ax = sns.countplot(x="PaymentMethod",data=df , hue='Churn')
for bars in ax.containers :
  ax.bar_label(bars)

plt.title("Customer Churn Count By PaymentMethod")
plt.show()